# Generated by Django 5.0.5 on 2024-05-07 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightId', models.AutoField(primary_key=True, serialize=False)),
                ('depTime', models.TimeField()),
                ('depDate', models.DateField()),
                ('arrTime', models.TimeField()),
                ('arrDate', models.DateField()),
                ('seatsAvailable', models.IntegerField()),
                ('ticketCost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passengerId', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=30)),
                ('lName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('planeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('numSeats', models.IntegerField()),
            ],
            options={
                'db_table': 'plane',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('whenBooked', models.DateTimeField()),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('flightFull', models.BooleanField()),
                ('flightId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingapp.flight')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingapp.passenger')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeId', models.AutoField(primary_key=True, serialize=False)),
                ('routeName', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('planeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bookingapp.plane')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='routeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='bookingapp.route'),
        ),
    ]
